### ISSUE TITLE
Create PVC finalizer 

### ISSUE THREAD

**Issue by ciaranRoche** [integr8ly/cloud-resource-operator#21]
## Issue
We need deletion protection on the PVC we create with both Redis and Postgres.

Currently when we create an openshift instance of Redis or Postgres we do not add a finalizer to the PVC. This could make it easier for accidental deletion of the PVC from the cluster. 

## Solution
We should add the finalizer when we [create the PVC](https://github.com/integr8ly/cloud-resource-operator/blob/master/pkg/providers/openshift/provider_postgres.go#L87).

We will also need to remove the finalizer when `DeletePostgres` is called.

All logic can be found in `pkg/providers/openshift/provider_postgres.go`

## Verify
- Have an Openshift or Kubernetes cluster 
- Run `make cluster/prepair`
- Make sure `deploy/crds/integreatly_v1alpha_postgres_cr.yaml` has the `spec/type` set to `workshop`
- Run `make cluster/seed/postgres`
- Run `make run`
- A postgres instance should be created in the `cloud-resource-operator`
- Ensure the finalizer has been added to the PVC
- Search for `postgres` in cluster, and remove the `resource` this should tripper the operator to begin deletion of the postgres instance
- Ensure the finalizer is removed and the `postgres` instance is removed completely from the cluster.

## Contribution
- Star Repo
- Fork Repo
- Create new branch on your fork
- Run `make test/unit` before pushing changes to branch
- Create PR against master branch on this Repo

**Comment by imazik** [comment]
@ciaranRoche i want to take this

**Comment by ciaranRoche** [comment]
@imazik great stuff, thanks for wanting to do both. Any questions just shout here.

**Comment by ciaranRoche** [comment]
closing, out of date
