### ISSUE TITLE
De-duplicate create kubernetes secret function

### ISSUE THREAD

**Issue by ciaranRoche** [integr8ly/cloud-resource-operator#22]
## Issue
Currently when creating a postgres resource in openshift and aws we need to pre create a secret within our cluster that will be used as the default user and password to the postgres instance. This work is duplicated in both `aws/provider_postgres.go` and `openshift/provider_postgres.go`

## Solution
Create a `postgres_util` in the `provider` directory which will de-duplicate the `buildDefaultPostgresSecret` function

## Verify
- Have an Openshift or Kubernetes cluster 
- Run `make cluster/prepair`
- Make sure `deploy/crds/integreatly_v1alpha_postgres_cr.yaml` has the `spec/type` set to `workshop`
- Run `make cluster/seed/postgres`
- Run `make run`
- A postgres instance should be created in the `cloud-resource-operator`
- Ensure the secret is created and contains `user`, `password` and `database`
- Search for `postgres` in cluster, and remove the `resource` this should tripper the operator to begin deletion of the postgres instance
- Ensure the finalizer is removed and the `postgres` instance is removed completely from the cluster.

## Contribution
- Star Repo
- Fork Repo
- Create new branch on your fork
- Run `make test/unit` before pushing changes to branch
- Create PR against master branch on this Repo

**Comment by imazik** [comment]
@ciaranRoche i want to take it.

**Comment by ciaranRoche** [comment]
@imazik that is great, feel free to work away on it. Any questions just shout here.

**Comment by ciaranRoche** [comment]
closing, out of date
